name: API Tests

on:
  push:
    branch: [main]
  pull_request:
    branch: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    stesp:
      - name: Checkout code
        uses: action/checkout@v4

      - name: Set up java 17
        uses: action/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Create config.properties from secrets
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          PATIENT_EMAIL: ${{ secrets.PATIENT_EMAIL }}
          PATIENT_PASSWORD: ${{ secrets.PATIENT_PASSWORD }}
          THERAPIST_EMAIL: ${{ secrets.THERAPIST_EMAIL }}
          THERAPIST_PASSWORD: ${{ secrets.THERAPIST_PASSWORD }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: |
          {
            echo "baseUrl=$BASE_URL"
            echo "patient.email=$PATIENT_EMAIL",
            echo "patient.password=$PATIENT_PASSWORD",
            echo "therapist.email=$THERAPIST_EMAIL",
            echo "therapist.password=$THERAPIST_PASSWORD",
            echo "admin.email=$ADMIN_EMAIL",
            echo "admin.password=$ADMIN_PASSWORD",
          } > src/test/resources/config.properties
      - name: Run tests
        run: mvn test
